In [25]:
from pathlib import Path
import pandas as pd
from IPython.display import display

print("Versão do pandas:", pd.__version__)

Versão do pandas: 2.2.3

In [24]:
url_dados = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv"
arquivo_local = Path("vaccinations.csv")

fonte = arquivo_local if arquivo_local.exists() else url_dados
df_vacinacao = pd.read_csv(fonte)
print(f"Fonte Utilizada: {fonte}")
print(f"Dimensões(linhas, colunas): {df_vacinacao.shape}")

Fonte Utilizada: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv
Dimensões(linhas, colunas): (196246, 16)

In [23]:
print(f"Primeiras 5 linhas")
display(df_vacinacao.head())

print("Tipos e Valoes não-nulos: ")
df_vacinacao.info()

print("Resumo das clnas numéricas: ")
display(df_vacinacao.describe())

Primeiras 5 linhas

,location,iso_code,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred
date,,,,,,,,,,,,,,,
2020-12-02,World,OWID_WRL,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0
2020-12-02,High income,OWID_HIC,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0
2020-12-02,Europe,OWID_EUR,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0
2020-12-02,Norway,NOR,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2020-12-03,Europe,OWID_EUR,0.0,0.0,NaN,NaN,1.0,1.0,0.0,0.0,NaN,NaN,0.0,1.0,0.0

Tipos e Valoes não-nulos:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 196246 entries, 2020-12-02 to 2024-08-14
Data columns (total 15 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   location                             196246 non-null  object
 1   iso_code                             196246 non-null  object
 2   total_vaccinations                   85417 non-null   float64
 3   people_vaccinated                    81132 non-null   float64
 4   people_fully_vaccinated              78061 non-null   float64
 5   total_boosters                       53600 non-null   float64
 6   daily_vaccinations_raw               70971 non-null   float64
 7   daily_vaccinations                   195029 non-null  float64
 8   total_vaccinations_per_hundred       85417 non-null   float64
 9   people_vaccinated_per_hundred        81132 non-null   float64
 10  people_fully_vaccinated_per_hundred  78061 non-null   float64
 11  total_boosters_per_hundred           53600 non-null   float64
 12  daily_vaccinations_per_million       195029 non-null  float64
 13  daily_people_vaccinated              192177 non-null  float64
 14  daily_people_vaccinated_per_hundred  192177 non-null  float64
dtypes: float64(13), object(2)
memory usage: 24.0+ MB
Resumo das clnas numéricas:

,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred
count,8.541700e+04,8.113200e+04,7.806100e+04,5.360000e+04,7.097100e+04,1.950290e+05,85417.000000,81132.000000,78061.000000,53600.000000,195029.000000,1.921770e+05,192177.000000
mean,5.616980e+08,2.487064e+08,2.286639e+08,1.505811e+08,7.398640e+05,2.838758e+05,124.279558,53.501409,48.680182,36.301489,1851.477596,1.060707e+05,0.074980
std,1.842160e+09,8.006461e+08,7.403763e+08,4.360697e+08,3.183064e+06,1.922352e+06,85.098042,29.379655,29.042282,30.218208,3117.828731,7.866884e+05,0.176216
min,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,1.970788e+06,1.050009e+06,9.644000e+05,6.022820e+05,2.010000e+03,2.790000e+02,44.770000,27.880000,21.220000,5.920000,106.000000,4.300000e+01,0.001000
50%,1.439435e+07,6.901088e+06,6.191345e+06,5.765440e+06,2.053100e+04,3.871000e+03,130.550000,64.300000,57.920000,35.905000,605.000000,7.710000e+02,0.014000
75%,1.161972e+08,5.093295e+07,4.773185e+07,4.019072e+07,1.736115e+05,3.180300e+04,194.990000,77.780000,73.610000,57.620000,2402.000000,9.307000e+03,0.073000
max,1.357877e+10,5.631264e+09,5.177943e+09,2.817381e+09,4.967320e+07,4.369181e+07,410.230000,129.070000,126.890000,150.470000,117113.000000,2.107127e+07,11.711000

In [28]:
df_vacinacao['date'] = pd.to_datetime(df_vacinacao['date'], errors='coerce')
print(f"Datas inválidas: {df_vacinacao['date'].isna().sum()}")
df_vacinacao.set_index('date', inplace=True)
df_vacinacao.sort_index(inplace=True)

print(f"Localidades distintas, incluindo agregados: {df_vacinacao['location'].nunique()}")
print(f"Intervalo Observado: {df_vacinacao.index.min()}, até {df_vacinacao.index.max()}")
display(df_vacinacao.head())

KeyError: 'date'

In [30]:
vacinacaoPorpais = df_vacinacao.groupby("location")

print(f"Quantidade de grupos: {len(vacinacaoPorpais)}")
print(f"Quantidade total de linhas: {len(df_vacinacao)}")
print(f"Cinco linhas por grupos produzem: {len(vacinacaoPorpais.head())}, linhas por conjunto")
print("Quantidade de registro nas primeiras cinco localidades: ")
display(vacinacaoPorpais.size().head())

Quantidade de grupos: 235
Quantidade total de linhas: 196246
Cinco linhas por grupos produzem: 1175, linhas por conjunto
Quantidade de registro nas primeiras cinco localidades:

location
Afghanistan    1043
Africa         1087
Albania         974
Algeria         584
Andorra         973
dtype: int64

In [36]:
df_Brasil = df_vacinacao[df_vacinacao["location"] == "Brazil"].copy()
colunas = ["location", "total_vaccinations", "total_vaccinations_per_hundred"]
display(df_Brasil[colunas].head())

brasil_acima_100_milhoes = df_Brasil[df_Brasil["total_vaccinations"] > 100_000_000]
print(f"Registros do Brasil de 100 milhões de doses: {len(brasil_acima_100_milhoes)}")
display(brasil_acima_100_milhoes[colunas].head())

           location  total_vaccinations  total_vaccinations_per_hundred
date
2021-01-17   Brazil               112.0                            0.00
2021-01-18   Brazil              1109.0                            0.00
2021-01-19   Brazil             13527.0                            0.01
2021-01-20   Brazil            105824.0                            0.05
2021-01-21   Brazil            193699.0                            0.09

Registros do Brasil de 100 milhões de doses: 531

           location  total_vaccinations  total_vaccinations_per_hundred
date
2021-06-30   Brazil         101167462.0                           46.99
2021-07-01   Brazil         102561737.0                           47.63
2021-07-02   Brazil         104047565.0                           48.32
2021-07-03   Brazil         104753510.0                           48.65
2021-07-04   Brazil         105097389.0                           48.81

In [37]:
df_vacinacao.dtypes

location                                object
iso_code                                object
total_vaccinations                     float64
people_vaccinated                      float64
people_fully_vaccinated                float64
total_boosters                         float64
daily_vaccinations_raw                 float64
daily_vaccinations                     float64
total_vaccinations_per_hundred         float64
people_vaccinated_per_hundred          float64
people_fully_vaccinated_per_hundred    float64
total_boosters_per_hundred             float64
daily_vaccinations_per_million         float64
daily_people_vaccinated                float64
daily_people_vaccinated_per_hundred    float64
dtype: object

In [39]:
top_vacinacao = df_vacinacao.sort_values(by="total_vaccinations", ascending=False)
display(top_vacinacao[["location", "total_vaccinations"]].head(10))

           location  total_vaccinations
date
2024-08-14    World        1.357877e+10
2024-08-13    World        1.357877e+10
2024-08-12    World        1.357877e+10
2024-08-11    World        1.357877e+10
2024-08-10    World        1.357876e+10
2024-08-09    World        1.357876e+10
2024-08-08    World        1.357876e+10
2024-08-07    World        1.357876e+10
2024-08-06    World        1.357876e+10
2024-08-05    World        1.357876e+10

In [49]:
from numpy._core.fromnumeric import sort
historico = df_vacinacao.reset_index()

df_localidades = historico[historico['iso_code'].str.len().eq(3)].copy()

df_ultimo = (
    df_localidades.dropna(subset=["date", "total_vaccinations"])
    .sort_values("date")
    .groupby("location", sort=False)
    .tail(1)
    .reset_index(drop=True)
)

top_10_paises = df_ultimo.sort_values(by="total_vaccinations", ascending=False).head(10)
print("Dez localidades do recorte com maior total de doses no último registro válido: ")
display(top_10_paises[["location", "date", "total_vaccinations"]])

Dez localidades do recorte com maior total de doses no último registro válido:

          location       date  total_vaccinations
68           China 2023-02-09        3.491077e+09
214          India 2024-08-12        2.206868e+09
106  United States 2023-05-09        6.767288e+08
83          Brazil 2023-03-22        4.864364e+08
174      Indonesia 2023-11-23        4.481999e+08
104          Japan 2023-05-07        3.837477e+08
208     Bangladesh 2024-07-01        3.617426e+08
169       Pakistan 2023-11-14        3.409741e+08
128        Vietnam 2023-06-30        2.664921e+08
36          Mexico 2022-10-07        2.231590e+08

In [82]:
df_mediaPaises = (
    df_localidades.groupby("location")["total_vaccinations"]

    .mean().reset_index()

)

resultado_por_pais = df_mediaPaises[['location', 'total_vaccinations']]

print(resultado_por_pais.head(10))

              location  total_vaccinations
0          Afghanistan        1.113981e+07
1              Albania        1.402001e+06
2              Algeria        1.065704e+07
3              Andorra        9.134781e+04
4               Angola        1.320656e+07
5             Anguilla        1.869680e+04
6  Antigua and Barbuda        7.876619e+04
7            Argentina        8.334411e+07
8              Armenia        1.087489e+06
9                Aruba        1.589524e+05